steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/dher405/RC-AI.git', 'my-repo']

- name: 'google/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute scp --recurse ./my-repo/ \
      "instance-20250326-191400":/RC-AI \
      --zone "us-central1-c" \
      --impersonate-service-account=cloud-build-deploy-238@primal-prism-169316.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  
