steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/dher405/RC-AI.git', 'my-repo']

  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Copying project to instance..."
        gcloud compute ssh david_herron74_gmail_com@instance-20250326-191400 \
          --zone=us-central1-c \
          --command "sudo mkdir -p /RC-AI && sudo chown david_herron74_gmail_com /RC-AI"

        gcloud compute scp --recurse ./my-repo/* \
          david_herron74_gmail_com@instance-20250326-191400:/RC-AI \
          --zone=us-central1-c

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
