steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/dher405/RC-AI.git', 'my-repo']

- name: 'google/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ~/.ssh
    gcloud secrets versions access latest --secret=cb-ssh-key > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan 34.171.61.152 >> ~/.ssh/known_hosts
    gcloud compute scp --recurse ./my-repo/ \
      root@34.171.61.152:/RC-AI \
      --zone "us-central1-c" \
      --ssh-key-file ~/.ssh/id_rsa

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

