steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/dher405/RC-AI.git', 'my-repo']

- name: 'google/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p ~/.ssh
    gcloud secrets versions access latest --secret=cb-ssh-key > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
    ssh-keyscan -H 34.171.61.152 >> ~/.ssh/known_hosts
    scp -i ~/.ssh/id_rsa -r ./my-repo/ root@34.171.61.152:/RC-AI

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

